### ISSUE TITLE
Review: User Profile & Register Volunteer Page

### ISSUE THREAD

**Issue by icce2k** [rainbowgeeks/rainbowgeeks#15]
## Overview

The focus for this code review will be centered around the User Profile & Register Volunteer pages.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

* review-01

## Files to review

* [RegisterVolunteer.jsx](https://github.com/rainbowgeeks/rainbowgeeks/blob/main/app/imports/ui/pages/AddProfile.jsx)
* [ProfilePage.jsx](https://github.com/rainbowgeeks/rainbowgeeks/blob/main/app/imports/ui/pages/ProfilePage.jsx)

## Checklists

* [Architecture](https://github.com/rainbowgeeks/rainbowgeeks/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/rainbowgeeks/rainbowgeeks/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/rainbowgeeks/rainbowgeeks/blob/main/checklists/js-checklist.md)
* [React](https://github.com/rainbowgeeks/rainbowgeeks/blob/main/checklists/react-checklist.md)

## Due date

February 01, 2022

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by cammoore** [comment]
## RegisterVolunteer.jsx

RegisterVolunteer link in the review goes to AddProfile.jsx

## ProfilePage.jsx

DE-04: L20: get rid of commented code.

L24: Bad comment. Get rid of all references to Stuff.
L35: Bad COMPONENT_ID.
L45, 50: What's up with all the Containers?

DE-07: L51-76: This should be a component we import and instantiate.
DE-07: L130-142: This should be a component.

L241: Get rid of Stuff.

**Comment by icce2k** [comment]
RegisterVolunteer.jsx
AR-01, AR-02, AR-03: all good
DE-01 - DE-08: all good
JS-01 - JS-07, ES-01, ES-02: all good
RE-01 - RE-10: all good

ProfilePage.jsx
AR-01, AR-02, AR-03: all good
DE-01 - DE-08: all good
JS-01 - JS-07, ES-01, ES-02: all good, condense imports?
RE-01 - RE-10: all good

**Comment by icce2k** [comment]
RegisterVolunteer.jsx
AR-01, AR-02, AR-03: all good
DE-01 - DE-08: all good
JS-01 - JS-07, ES-01, ES-02: all good
RE-01 - RE-10: all good

ProfilePage.jsx
AR-01, AR-02, AR-03: all good
DE-01 - DE-08: all good
JS-01 - JS-07, ES-01, ES-02: all good, condense imports?
RE-01 - RE-10: all good

**Comment by Jonathan-Ma** [comment]
AR: All good
DE-04: Eliminate large comment blocks.

**Comment by buccatm** [comment]
ProfilePage.jsx
AR-01, AR-02, AR-03: is good
JS-07: The comment is not related to page-profile
ES-Lint: Error, remove the stuffs not used

**Comment by Lazokris** [comment]
RegisterVolunteer.jsx
AR: all good
DE: all good
JS: Delete stuff collection

ProfilePage.jsx
AR: all good
JS: Delete Commented import, delete stuff collection

**Comment by Matt-Ito** [comment]
RegisterVolunteer.jsx
AR: Looks good
JS: Delete stuff

ProfilePage.jsx
AR: Seems ok
JS: Delete stuff
