### ISSUE TITLE
Review: FilterOpportunities & Landing

### ISSUE THREAD

**Issue by Lazokris** [rainbowgeeks/rainbowgeeks#28]
## Overview

The focus for this code review will be centered around the  FilterOpportunities and Landing 
 page.    

Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-02

## Files to review

* [FilterOpportunities.jsx](https://github.com/rainbowgeeks/rainbowgeeks/blob/main/app/imports/ui/pages/FilterOpportunities.jsx)
* [Landing.jsx](https://github.com/rainbowgeeks/rainbowgeeks/blob/main/app/imports/ui/pages/Landing.jsx)

## Checklists

* [Architecture](https://github.com/rainbowgeeks/rainbowgeeks/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/rainbowgeeks/rainbowgeeks/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/rainbowgeeks/rainbowgeeks/blob/main/checklists/js-checklist.md)
* [React](https://github.com/rainbowgeeks/rainbowgeeks/blob/main/checklists/react-checklist.md)

## Due date

February 08, 12 pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by Jonathan-Ma** [comment]
FilterOpportunities looks good except there are some minor eslint problems starting from line 65.

**Comment by Lazokris** [comment]
LandingPage.jsx
- Javascript: looks good
- React: looks good
   - Things to add:
      -  Add other pages like browse Opp. by Category
      -  Latest Opp. 

FilterOpportunitiesPage.jsx
- Javascript:
-  Take out console.log
- Add comment for FilterOpportunities function and withTracker
-  Things to add:
    -  Fix page layout
    -  add submit function
- React:
- looks good
- things to work on:
    - Fix component and page interaction 
    -  Maybe combine CategoryOpp and Filter Page together

**Comment by JohnSuelen** [comment]
FilterOpportunitiesPage.jsx

- AR: good
- DE: good
- JS: JS-06: Avoid console.logs, line 49
There may be ESLint errors but unable to check right now.
- React: good

LandingPage.jsx

- AR: good
- DE: good
- JS: good
There may be ESLint errors but unable to check right now.
- React: good
Just needs more content.

**Comment by cammoore** [comment]
## FilterOpportunities.jsx

L20 - 38: Might want to make these values constants in an object. Something
like:

export const OpportunityOrder = {
  UPCOMING: "Upcoming",
  LATEST: "Latest",
  NEARBY: "Nearby",
  A_Z: "A-Z",
}

L67: Think about how you are going to filter opportunities before you
return the div.

## Landing.jsx

L11, 13: Are these really items, or are they Headers?

**Comment by buccatm** [comment]
LandingPage

AR: all good
DE: all good
JS: all good
React: all good

FilterOpportunities

Architecture: All fine
Design:
01-no duplicates
02-no nested conditionals
03-no dead end codes
04-no large comments
05-line 61, 47 eslint-disable-next-line react/display-name, unnecessary comment, should
be resolveable
06-code is readable
07-code is DRY
08-ok

JS:
01-name is constructed appropriatley
02-did not need it
03-did not need it
04-yes
05-good
06-line 49, used console.log to display submited datas
07-did not use or do JDOC
====== ES =====
01-line 61, 47 eslint error occured
02-fine

React:
01-fine
02-ok
03-fine
04-fine
05-fine
06-fine
07-fine
08-fine
09-fine
10-fine

**Comment by icce2k** [comment]
FilterOpportunities.jsx
Architecture: all good

Design: all good

JS: fix indent errors

React: all good


Landing.jsx
Architecture: all good

Design: all good

JS: all good

React: all good

**Comment by Matt-Ito** [comment]
FilterOpportunities.jsx
JavaScript and react look good.
Probably ESLint errors?
Architecture looks good.
Design also looks good.

Landing.jsx
JavaScript and React look good. 
Maybe add more content in future.
Architecture looks good.
Design also looks good.
