### ISSUE TITLE
Review: AdminProfile & OrganizationLibrary

### ISSUE THREAD

**Issue by icce2k** [rainbowgeeks/rainbowgeeks#33]
## Overview

The focus for this code review will be centered around the AdminProfile & OrganizationLibrary pages.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-03

## Files to review

* [AdminProfile.jsx](../blob/main/app/imports/ui/pages/AdminProfile.jsx)
* [OrganizationLibrary.jsx](../blob/main/app/imports/ui/pages/OrganizationLibrary.jsx)

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)

## Due date

15, February 2022

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by buccatm** [comment]
AdminProfile
JS
1-6 are fine
7-line 8, stuffs is not related to AdminProfile, Consider removing the Stuffs Collection from adminProfile

ReacT
1-lines 15-110 consider using Components
2-9: are fine


Organization Library
7-line 8 stuffs comment is not related to the organization Library

REACT
1-lines 30-72, consider breaking into components
2-9: are fine

**Comment by icce2k** [comment]
AdminProfile.jsx
Architecture: all good

Design: get rid of unused code. 'Stuffs' related code.

JavaScript: all good.

React: mostly good. a lot of complicated components.


OrganizationLibrary.jsx
Architecture: all good

Design: get rid of unused code. 'Stuffs' related code.

JavaScript: all good.

React: mostly good. a lot of complicated components.

**Comment by cammoore** [comment]
## AdminProfile.jsx

L9: Stuff!
L13: Meteor logo?
L26-78: Can we create an object and use the values of the object to
render the table?
L97: stuffs?
L108: Stuffs?

## OrganizationLibrary.jsx

L9: Ignoring the opportunities being passed in from withTracker.
L31-71: Can we create an array of object to render the cards? Or use
the organizations from the collection?

**Comment by Jonathan-Ma** [comment]
AdminProfile.jsx
design: stuffs code gotta go
JS: adminProfile can be removed
arch: all good
react: all good

Organization Library.jsx
arch: all good
design: stuffs code gotta go
JS: no problem
arch: all good
react: all good

**Comment by Lazokris** [comment]
• AdminProfile.jsx
Javascript:
	◦ Looks good.
	◦ maybe take out stuff collection
React:
	◦ Looks good.
• OrganizationLibrary.jsx
Javascript:
	◦ Looks good.
React:
	◦ Looks good.

**Comment by Matt-Ito** [comment]
AdminProfile.jsx
JS looks good
Maybe take out Stuff if we do not need it
React looks good

OrganizationLibrary.jsx
JS looks good
Take out Stuff if we do not need it
React looks good
